default: &default
  adapter: postgresql
  pool: my_database
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000

test:
  <<: *default
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000

production:
  <<: *default
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
